In [2]:
from numpy import exp, array, random, dot
import numpy as np

In [3]:
class NeuronLayer():
    def __init__(self, number_of_neurons, number_of_inputs_per_neuron):
        self.synaptic_weights = 2 * random.random((number_of_inputs_per_neuron, number_of_neurons)) - 1

In [4]:
class NeuralNetwork():
    def __init__(self, layer1, layer2):
        self.layer1 = layer1
        self.layer2 = layer2

    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in xrange(number_of_training_iterations):
            output_from_layer_1, output_from_layer_2 = self.think(training_set_inputs)

            layer2_error = training_set_outputs - output_from_layer_2
            layer2_delta = layer2_error * self.__sigmoid_derivative(output_from_layer_2)

            layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
            layer1_delta = layer1_error * self.__sigmoid_derivative(output_from_layer_1)

            layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
            layer2_adjustment = output_from_layer_1.T.dot(layer2_delta)

            self.layer1.synaptic_weights += layer1_adjustment
            self.layer2.synaptic_weights += layer2_adjustment

    def think(self, inputs):
        output_from_layer1 = self.__sigmoid(dot(inputs, self.layer1.synaptic_weights))
        output_from_layer2 = self.__sigmoid(dot(output_from_layer1, self.layer2.synaptic_weights))
        return output_from_layer1, output_from_layer2

    def print_weights(self):
        print "Layer 1 (4 neurons, each with 3 inputs): "
        print self.layer1.synaptic_weights
        print "Layer 2 (1 neuron, with 4 inputs):"
        print self.layer2.synaptic_weights
    
    def print_value(self, weight_output):
        if(weight_output < 0.5):
            print("Output is : "+str(0))
        else:
            print("Output is : "+str(1))

In [22]:
if __name__ == "__main__":

    random.seed(1)

    # Create layer 1 (4 neurons, each with 2 inputs)
    layer1 = NeuronLayer(4, 2)

    # Create layer 2 (a single neuron with 4 inputs)
    layer2 = NeuronLayer(1, 4)

    # Combine the layers to create a neural network
    neural_network = NeuralNetwork(layer1, layer2)

    print "Stage 1) Random starting synaptic weights: "
    neural_network.print_weights()

    # The training set. We have 7 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[0, 0], [0, 1], [1, 0], [1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network using the training set.
    # Do it 60,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 60000)

    print "Stage 2) New synaptic weights after training: "
    neural_network.print_weights()

    # Test the neural network with a new situation.
    print "Stage 3) Considering a new situation [1, 1] -> ?: "
    hidden_state, output1 = neural_network.think(array([0, 0]))
    hidden_state, output2 = neural_network.think(array([0, 1]))
    hidden_state, output3 = neural_network.think(array([1, 0]))
    hidden_state, output4 = neural_network.think(array([1, 1]))    

    neural_network.print_value(output1)
    neural_network.print_value(output2)
    neural_network.print_value(output3)
    neural_network.print_value(output4)

Stage 1) Random starting synaptic weights: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]]
    Layer 2 (1 neuron, with 4 inputs):
[[-0.20646505]
 [ 0.07763347]
 [-0.16161097]
 [ 0.370439  ]]
Stage 2) New synaptic weights after training: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[ 3.29466269  4.11744925 -6.10247774 -7.61008987]
 [-1.43804391 -8.34688493 -5.96873454  3.54393008]]
    Layer 2 (1 neuron, with 4 inputs):
[[ -6.23251593]
 [ 11.1608825 ]
 [-21.11369016]
 [  6.55100947]]
Stage 3) Considering a new situation [1, 1] -> ?: 
Output is : 0
Output is : 1
Output is : 1
Output is : 0
